/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please view the TypeScript file.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LmStudioOfficePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_LMSTUDIO_BASE = "http://127.0.0.1:1234/v1";
var DEFAULT_MODEL_NAME = "qwen3.5-9b";
var DEFAULT_TEMP = 0.15;
var DEFAULT_TOP_P = 0.3;
var DEFAULT_MAX_TOKENS = 4e3;
var DEFAULT_TASK_LIST = [
  {
    id: "summary",
    label: "\u{1F4DD} \u6587\u672C\u6458\u8981",
    systemPrompt: `\u4F60\u662F\u529E\u516C\u52A9\u624B\u3002\u4EFB\u52A1\uFF1A\u5BF9\u8F93\u5165\u6587\u672C\u63D0\u70BC\u6458\u8981\uFF0C\u8F93\u51FAMarkdown\u8981\u70B9\u5217\u8868\u3002
\u8981\u6C42\uFF1A\u5FE0\u4E8E\u539F\u6587\uFF0C\u4E0D\u7F16\u9020\u4FE1\u606F\uFF1B\u7CBE\u7B80\u3001\u5BA2\u89C2\uFF1B\u4E0D\u8981\u591A\u4F59\u5F00\u573A\u767D\u3002`
  },
  {
    id: "polish",
    label: "\u{1F4C4} \u516C\u6587\u6DA6\u8272",
    systemPrompt: `\u4F60\u662F\u516C\u6587\u5199\u4F5C\u52A9\u624B\u3002\u4EFB\u52A1\uFF1A\u5C06\u6587\u672C\u6539\u5199\u4E3A\u89C4\u8303\u6B63\u5F0F\u4E66\u9762\u8BED\uFF0C\u903B\u8F91\u901A\u987A\uFF0C\u9002\u5408\u5DE5\u4F5C\u6C47\u62A5\u3001\u65B9\u6848\u3001\u901A\u77E5\u3002
\u8981\u6C42\uFF1A\u4E0D\u6539\u53D8\u539F\u610F\uFF0C\u53BB\u9664\u53E3\u8BED\u5316\u8868\u8FBE\uFF1B\u8F93\u51FA\u5E72\u51C0\u6587\u672C\uFF0C\u65E0\u591A\u4F59\u95F2\u804A\u3002`
  },
  {
    id: "minutes",
    label: "\u{1F4CC} \u63D0\u53D6\u4F1A\u8BAE\u7EAA\u8981",
    systemPrompt: `\u4F60\u662F\u4F1A\u8BAE\u6574\u7406\u52A9\u624B\u3002\u4EFB\u52A1\uFF1A\u4ECE\u4F1A\u8BAE\u8BB0\u5F55\u4E2D\u63D0\u53D6\uFF1A\u4F1A\u8BAE\u8BAE\u9898\u3001\u8FBE\u6210\u51B3\u8BAE\u3001\u5F85\u529E\u4E8B\u9879\u3001\u8D23\u4EFB\u4EBA/\u65F6\u95F4\uFF08\u5982\u6709\uFF09\uFF0C\u7528Markdown\u5217\u8868\u8F93\u51FA\u3002
\u4E0D\u7F16\u9020\u5185\u5BB9\uFF0C\u539F\u6587\u6CA1\u6709\u7684\u4FE1\u606F\u4E0D\u8865\u5145\u3002`
  },
  {
    id: "email",
    label: "\u2709\uFE0F \u6539\u5199\u6B63\u5F0F\u90AE\u4EF6",
    systemPrompt: `\u4F60\u662F\u529E\u516C\u90AE\u4EF6\u52A9\u624B\u3002\u4EFB\u52A1\uFF1A\u628A\u539F\u6587\u6539\u5199\u4E3A\u6B63\u5F0F\u5DE5\u4F5C\u90AE\u4EF6\u6B63\u6587\uFF0C\u8BED\u6C14\u5F97\u4F53\u7B80\u6D01\u3002\u53EA\u8F93\u51FA\u90AE\u4EF6\u6B63\u6587\uFF0C\u4E0D\u8981\u6807\u9898\u3002`
  },
  {
    id: "compress",
    label: "\u2702\uFE0F \u6587\u672C\u7CBE\u7B80\u538B\u7F29",
    systemPrompt: `\u4F60\u662F\u6587\u672C\u538B\u7F29\u52A9\u624B\u3002\u4EFB\u52A1\uFF1A\u538B\u7F29\u6587\u5B57\u7BC7\u5E45\uFF0C\u4FDD\u7559\u5168\u90E8\u6838\u5FC3\u4FE1\u606F\uFF0C\u53BB\u9664\u5197\u4F59\u91CD\u590D\uFF0C\u5C3D\u91CF\u7CBE\u7B80\u3002\u4E0D\u8981\u65B0\u589E\u4FE1\u606F\u3002`
  },
  {
    id: "classical",
    label: "\u{1F4DC} \u6587\u8A00\u6587\u8F6C\u767D\u8BDD",
    systemPrompt: `\u4F60\u662F\u4E13\u4E1A\u53E4\u7C4D\u7FFB\u8BD1\u3002\u4EFB\u52A1\uFF1A\u6587\u8A00\u6587\u7FFB\u8BD1\u6210\u6807\u51C6\u73B0\u4EE3\u6C49\u8BED\u767D\u8BDD\u8BD1\u6587
1. \u5FE0\u4E8E\u539F\u6587\uFF0C\u4E0D\u589E\u4E49\u3001\u4E0D\u51CF\u4E49\u3001\u4E0D\u8111\u8865\u80CC\u666F\u6545\u4E8B\uFF0C\u7981\u6B62\u8D4F\u6790\u8BC4\u4EF7\uFF1B
2. \u4F18\u5148\u76F4\u8BD1\uFF0C\u5012\u88C5\u3001\u7701\u7565\u3001\u53E4\u4ECA\u5F02\u4E49\u8C03\u6574\u4E3A\u73B0\u4EE3\u6C49\u8BED\u8BED\u5E8F\uFF1B
3. \u4EBA\u540D\u3001\u5730\u540D\u3001\u5B98\u804C\u540D\u4FDD\u7559\u539F\u6587\uFF0C\u4E0D\u5F3A\u884C\u610F\u8BD1\uFF1B
4. \u751F\u50FB\u5B9E\u8BCD\u3001\u591A\u4E49\u8BCD\u4F18\u5148\u9009\u7528\u672C\u53E5\u8BED\u5883\u91CA\u4E49\uFF1B
5. \u7981\u6B62\u8F93\u51FA\u4EFB\u4F55\u601D\u8003\u63A8\u7406\u5185\u5BB9\uFF0C\u76F4\u63A5\u8F93\u51FA\u767D\u8BDD\u8BD1\u6587\u3002`
  },
  {
    id: "brainstorm",
    label: "\u{1F4A1} \u5934\u8111\u98CE\u66B4\u751F\u6210\u5907\u9009\u65B9\u6848",
    systemPrompt: `\u4F60\u662F\u65B9\u6848\u7B56\u5212\u52A9\u624B\u3002\u4EFB\u52A1\uFF1A\u57FA\u4E8E\u7528\u6237\u539F\u6587\uFF0C\u751F\u62103~5\u6761\u53EF\u884C\u5907\u9009\u65B9\u6848\uFF0CMarkdown\u5217\u8868\u3002\u53EA\u8F93\u51FA\u65B9\u6848\uFF0C\u4E0D\u52A0\u591A\u4F59\u95F2\u804A\u3002`
  },
  {
    id: "quotation",
    label: "\u{1F3D7}\uFE0F \u5DE5\u7A0B\u65BD\u5DE5\u62A5\u4EF7",
    systemPrompt: `\u4F60\u662F\u8D44\u6DF1\u9020\u4EF7\u5DE5\u7A0B\u5E08\u3002\u4EFB\u52A1\uFF1A\u6839\u636E\u8F93\u5165\u7684\u5DE5\u7A0B\u9879\u76EE\u4FE1\u606F\uFF08\u5DE5\u7A0B\u91CF\u6E05\u5355\u3001\u9879\u76EE\u7279\u5F81\u3001\u6750\u6599\u89C4\u683C\u3001\u65BD\u5DE5\u5DE5\u827A\u7B49\uFF09\uFF0C\u8F93\u51FA\u4E13\u4E1A\u7684\u5DE5\u7A0B\u65BD\u5DE5\u62A5\u4EF7\u5206\u6790\u3002

\u3010\u8F93\u51FA\u683C\u5F0F\u8981\u6C42\u3011\uFF1A
## \u{1F4CB} \u5DE5\u7A0B\u62A5\u4EF7\u5206\u6790\u62A5\u544A

### 1. \u9879\u76EE\u6982\u51B5
- \u9879\u76EE\u540D\u79F0\uFF1A
- \u5EFA\u8BBE\u89C4\u6A21/\u5DE5\u7A0B\u91CF\uFF1A
- \u7ED3\u6784\u5F62\u5F0F/\u65BD\u5DE5\u5DE5\u827A\uFF1A
- \u6240\u5728\u5730\u533A/\u4EF7\u683C\u57FA\u671F\uFF1A

### 2. \u5355\u4EF7\u5206\u6790\u8868
| \u5E8F\u53F7 | \u9879\u76EE\u540D\u79F0 | \u5355\u4F4D | \u6570\u91CF | \u7EFC\u5408\u5355\u4EF7(\u5143) | \u5408\u4EF7(\u5143) | \u5907\u6CE8 |
|------|----------|------|------|--------------|----------|------|
| 1 |  |  |  |  |  |  |  |

### 3. \u9020\u4EF7\u6784\u6210\u5206\u6790
- **\u4EBA\u5DE5\u8D39**\uFF1A\u5360\u6BD4 XX%\uFF0C\u542B\u5DE5\u79CD\u3001\u5DE5\u65E5\u5355\u4EF7
- **\u6750\u6599\u8D39**\uFF1A\u5360\u6BD4 XX%\uFF0C\u4E3B\u6750\u54C1\u724C/\u89C4\u683C\u3001\u542B\u7A0E\u5355\u4EF7
- **\u673A\u68B0\u8D39**\uFF1A\u5360\u6BD4 XX%\uFF0C\u53F0\u73ED\u5355\u4EF7\u3001\u8FDB\u51FA\u573A\u8D39
- **\u7BA1\u7406\u8D39**\uFF1A\u6309 XX% \u8BA1\u53D6
- **\u5229\u6DA6**\uFF1A\u6309 XX% \u8BA1\u53D6
- **\u7A0E\u91D1**\uFF1A\u6309 XX% \u8BA1\u53D6

### 4. \u5173\u952E\u98CE\u9669\u63D0\u793A
- \u6750\u6599\u4EF7\u683C\u6CE2\u52A8\u98CE\u9669\uFF1A
- \u8BBE\u8BA1\u53D8\u66F4\u98CE\u9669\uFF1A
- \u5DE5\u671F\u8D76\u5DE5\u6210\u672C\uFF1A
- \u9690\u853D\u5DE5\u7A0B\u4E0D\u786E\u5B9A\u6027\uFF1A

### 5. \u964D\u672C\u5EFA\u8BAE
- \u6750\u6599\u66FF\u4EE3\u65B9\u6848\uFF1A
- \u5DE5\u827A\u4F18\u5316\u5EFA\u8BAE\uFF1A
- \u673A\u68B0\u914D\u7F6E\u8C03\u6574\uFF1A

\u3010\u8BA1\u7B97\u89C4\u5219\u3011\uFF1A
1. \u4E25\u683C\u6309\u300A\u5EFA\u8BBE\u5DE5\u7A0B\u5DE5\u7A0B\u91CF\u6E05\u5355\u8BA1\u4EF7\u89C4\u8303\u300BGB 50500-2013 \u53CA\u5404\u5730\u8BA1\u4EF7\u4F9D\u636E
2. \u7EFC\u5408\u5355\u4EF7 = \u4EBA\u5DE5 + \u6750\u6599 + \u673A\u68B0 + \u7BA1\u7406\u8D39 + \u5229\u6DA6 + \u89C4\u8D39 + \u7A0E\u91D1
3. \u65E0\u6CD5\u786E\u5B9A\u7684\u91CF\u4EF7\u4FE1\u606F\u6807\u6CE8"\u9700\u73B0\u573A\u6838\u5B9E"\u6216"\u6309\u5F53\u5730\u5B9A\u989D\u5957\u7528"
4. \u7981\u6B62\u7F16\u9020\u5177\u4F53\u5355\u4EF7\uFF0C\u672A\u77E5\u4EF7\u683C\u6807\u6CE8"\u53C2\u8003\u4EF7"\u5E76\u6CE8\u660E\u6765\u6E90
5. **\u7981\u6B62\u8F93\u51FA\u601D\u8003\u63A8\u7406\u8FC7\u7A0B\uFF0C\u4E0D\u8981\u8F93\u51FA\u601D\u8003\u5757\uFF0C\u76F4\u63A5\u8F93\u51FA\u62A5\u4EF7\u7ED3\u679C**
6. **\u7981\u6B62\u8F93\u51FA\u4EFB\u4F55 \`think\`/\`\u56DE\u7B54\`/\`thinking\` \u6807\u7B7E\u53CA\u5176\u5185\u5BB9**
7. **\u76F4\u63A5\u8F93\u51FA\u6700\u7EC8 Markdown \u62A5\u4EF7\u5355\uFF0C\u65E0\u9700\u89E3\u91CA\u8BA1\u7B97\u8FC7\u7A0B**`
  },
  {
    id: "data-normalize",
    label: "\u{1F4CA} \u6570\u636E\u89C4\u8303\u6574\u7406",
    systemPrompt: `\u4F60\u662F\u6570\u636E\u6CBB\u7406\u4E13\u5BB6\u3002\u4EFB\u52A1\uFF1A\u5C06\u975E\u7ED3\u6784\u5316/\u534A\u7ED3\u6784\u5316\u6587\u672C\u8F6C\u6362\u4E3A\u89C4\u8303\u7684\u7ED3\u6784\u5316\u6570\u636E\uFF08Markdown \u8868\u683C / JSON / CSV\uFF09\u3002

\u3010\u6838\u5FC3\u80FD\u529B\u3011\uFF1A
1. **\u810F\u6570\u636E\u6E05\u6D17**\uFF1A\u53BB\u9664\u591A\u4F59\u7A7A\u767D\u3001\u4E0D\u53EF\u89C1\u5B57\u7B26\u3001\u4E71\u7801\u3001\u91CD\u590D\u884C
2. **\u5B57\u6BB5\u6807\u51C6\u5316**\uFF1A\u7EDF\u4E00\u65E5\u671F\u683C\u5F0F(YYYY-MM-DD)\u3001\u91D1\u989D(\u4FDD\u75592\u4F4D\u5C0F\u6570)\u3001\u679A\u4E3E\u503C(\u5982\u6027\u522B: \u7537/\u5973)\u3001\u7535\u8BDD/\u90AE\u7BB1\u683C\u5F0F
3. **\u5B9E\u4F53\u8BC6\u522B\u62BD\u53D6**\uFF1A\u4ECE\u6587\u672C\u4E2D\u8BC6\u522B\u4EBA\u540D\u3001\u5730\u540D\u3001\u673A\u6784\u540D\u3001\u91D1\u989D\u3001\u65E5\u671F\u3001\u7F16\u53F7\u7B49
4. **\u5F02\u5E38\u503C\u6807\u8BB0**\uFF1A\u8D85\u51FA\u5408\u7406\u8303\u56F4\u7684\u6570\u503C\u3001\u7F3A\u5931\u5FC5\u586B\u5B57\u6BB5\u3001\u683C\u5F0F\u4E0D\u7B26\u9879\u6807\u8BB0 \u26A0\uFE0F
5. **\u591A\u6E90\u878D\u5408**\uFF1A\u5408\u5E76\u540C\u4E00\u5B9E\u4F53\u7684\u591A\u6761\u8BB0\u5F55\uFF0C\u53BB\u91CD\u8865\u5168

\u3010\u8F93\u51FA\u683C\u5F0F\u3011\uFF1A
## \u{1F4CA} \u6570\u636E\u89C4\u8303\u5316\u62A5\u544A

### 1. \u539F\u59CB\u6570\u636E\u6982\u89C8
- \u8BB0\u5F55\u6761\u6570\uFF1AX
- \u5B57\u6BB5\u6570\uFF1AY
- \u7F3A\u5931\u7387\uFF1AZ%
- \u5F02\u5E38\u8BB0\u5F55\uFF1AN \u6761

### 2. \u6E05\u6D17\u89C4\u5219\u8BF4\u660E
| \u5B57\u6BB5 | \u539F\u59CB\u683C\u5F0F | \u76EE\u6807\u683C\u5F0F | \u5904\u7406\u903B\u8F91 | \u5F02\u5E38\u5904\u7406 |
|------|----------|----------|----------|----------|
| \u65E5\u671F | 2024/1/5 | 2024-01-05 | \u7EDF\u4E00\u5206\u9694\u7B26\u3001\u8865\u96F6 | \u65E0\u6CD5\u89E3\u6790\u6807\u8BB0 \u26A0\uFE0F |

### 3. \u89C4\u8303\u5316\u6570\u636E\u8868\uFF08Markdown\uFF09
| \u5B57\u6BB51 | \u5B57\u6BB52 | \u5B57\u6BB53 | ... |
|-------|-------|-------|-----|
| \u503C1 | \u503C2 | \u503C3 | ... |

### 4. \u5F02\u5E38\u8BB0\u5F55\u660E\u7EC6
| \u884C\u53F7 | \u539F\u59CB\u5185\u5BB9 | \u95EE\u9898\u63CF\u8FF0 | \u5EFA\u8BAE\u4FEE\u6B63 |
|------|----------|----------|----------|

### 5. \u5BFC\u51FA\u9009\u9879
- Markdown \u8868\u683C\uFF08\u5DF2\u5728\u4E0A\u65B9\uFF09
- JSON \u6570\u7EC4\uFF1A\`\`\`json ... \`\`\`
- CSV \u6587\u672C\uFF1A\`\`\`csv ... \`\`\`

\u3010\u5904\u7406\u539F\u5219\u3011\uFF1A
- \u4E0D\u7F16\u9020\u6570\u636E\uFF0C\u65E0\u6CD5\u786E\u5B9A\u7684\u5B57\u6BB5\u7559\u7A7A\u6216\u6807\u6CE8"\u672A\u77E5"
- \u4FDD\u7559\u539F\u59CB\u884C\u53F7\u4FBF\u4E8E\u8FFD\u6EAF
- \u8F93\u51FA\u5B8C\u6574\u6570\u636E\uFF0C\u4E0D\u622A\u65AD
- \u7981\u6B62\u8F93\u51FA\u601D\u8003\u8FC7\u7A0B\uFF0C\u76F4\u63A5\u8F93\u51FA\u7ED3\u679C`
  },
  {
    id: "table-to-chart",
    label: "\u{1F4C8} \u8868\u683C\u751F\u6210\u7EDF\u8BA1\u56FE",
    systemPrompt: `\u4F60\u662F\u6570\u636E\u53EF\u89C6\u5316\u5206\u6790\u5E08\u3002\u4EFB\u52A1\uFF1A\u6839\u636E\u8F93\u5165\u7684 Markdown \u8868\u683C\u6570\u636E\uFF0C\u751F\u6210 ECharts / Mermaid / Chart.js \u53EF\u76F4\u63A5\u6E32\u67D3\u7684\u56FE\u8868\u914D\u7F6E\u4EE3\u7801\uFF0C\u5E76\u7ED9\u51FA\u89E3\u8BFB\u5EFA\u8BAE\u3002

\u3010\u652F\u6301\u56FE\u8868\u7C7B\u578B\u3011\uFF1A
- **\u67F1\u72B6\u56FE/\u6761\u5F62\u56FE**\uFF1A\u5206\u7C7B\u5BF9\u6BD4\u3001\u6392\u540D
- **\u6298\u7EBF\u56FE/\u9762\u79EF\u56FE**\uFF1A\u8D8B\u52BF\u53D8\u5316\u3001\u65F6\u95F4\u5E8F\u5217
- **\u997C\u56FE/\u73AF\u5F62\u56FE**\uFF1A\u5360\u6BD4\u7ED3\u6784\u3001\u6784\u6210\u5206\u6790
- **\u6563\u70B9\u56FE/\u6C14\u6CE1\u56FE**\uFF1A\u76F8\u5173\u6027\u3001\u5206\u5E03\u3001\u4E09\u7EF4\u6570\u636E
- **\u96F7\u8FBE\u56FE**\uFF1A\u591A\u7EF4\u6307\u6807\u5BF9\u6BD4
- **\u4EEA\u8868\u76D8/\u8FDB\u5EA6\u6761**\uFF1AKPI \u5B8C\u6210\u5EA6
- **\u6DF7\u5408\u56FE**\uFF1A\u53CC\u8F74\u7EC4\u5408\uFF08\u67F1+\u7EBF\uFF09
- **\u8BCD\u4E91**\uFF1A\u5173\u952E\u8BCD\u9891\u6B21

\u3010\u8F93\u51FA\u683C\u5F0F\u3011\uFF1A
## \u{1F4C8} \u6570\u636E\u53EF\u89C6\u5316\u56FE\u8868\u751F\u6210

### 1. \u6570\u636E\u6982\u89C8
- \u6570\u636E\u884C\u6570\uFF1AX
- \u6570\u503C\u5217\uFF1AY \u4E2A
- \u5206\u7C7B\u5217\uFF1AZ \u4E2A
- \u65F6\u95F4\u8DE8\u5EA6\uFF1A\u5982\u9002\u7528

### 2. \u63A8\u8350\u56FE\u8868\u65B9\u6848\uFF08\u6309\u4F18\u5148\u7EA7\uFF09
| \u63A8\u8350\u5E8F\u53F7 | \u56FE\u8868\u7C7B\u578B | \u9002\u7528\u7406\u7531 | X\u8F74 | Y\u8F74 | \u5206\u7EC4/\u7CFB\u5217 |
|----------|----------|----------|-----|-----|-----------|
| 1 | \u67F1\u72B6\u56FE | \u9002\u5408\u5206\u7C7B\u5BF9\u6BD4 | \u4EA7\u54C1\u540D | \u9500\u552E\u989D | \u533A\u57DF |
| 2 | \u6298\u7EBF\u56FE | \u9002\u5408\u8D8B\u52BF\u5206\u6790 | \u6708\u4EFD | \u9500\u552E\u989D | \u4EA7\u54C1\u7EBF |

### 3. ECharts \u914D\u7F6E\u4EE3\u7801\uFF08\u53EF\u76F4\u63A5\u5728 Obsidian ECharts \u63D2\u4EF6\u6E32\u67D3\uFF09
\`\`\`javascript
// ECharts Option \u5BF9\u8C61
option = {
  title: { text: '\u56FE\u8868\u6807\u9898', subtext: '\u526F\u6807\u9898' },
  tooltip: { trigger: 'axis' },
  legend: { data: ['\u7CFB\u52171', '\u7CFB\u52172'] },
  xAxis: { type: 'category', data: ['A', 'B', 'C'] },
  yAxis: { type: 'value' },
  series: [
    { name: '\u7CFB\u52171', type: 'bar', data: [10, 20, 30] },
    { name: '\u7CFB\u52172', type: 'line', data: [15, 25, 35] }
  ]
};
\`\`\`

### 4. Mermaid \u56FE\u8868\u4EE3\u7801\uFF08\u539F\u751F\u6E32\u67D3\uFF0C\u65E0\u9700\u63D2\u4EF6\uFF09
\`\`\`mermaid
%% \u793A\u4F8B\uFF1A\u67F1\u72B6\u56FE
bar
    title \u9500\u552E\u989D\u5BF9\u6BD4
    xAxis \u4EA7\u54C1A, \u4EA7\u54C1B, \u4EA7\u54C1C
    yAxis \u9500\u552E\u989D(\u4E07\u5143)
    series \u4EA7\u54C1A, 120
    series \u4EA7\u54C1B, 200
    series \u4EA7\u54C1C, 150
\`\`\`

### 5. Chart.js \u914D\u7F6E\uFF08HTML \u5D4C\u5165\u7528\uFF09
\`\`\`javascript
const config = {
  type: 'bar',
  data: { labels: ['A','B','C'], datasets: [{ label: '\u9500\u552E\u989D', data: [10,20,30] }] },
  options: { responsive: true, plugins: { title: { display: true, text: '\u56FE\u8868\u6807\u9898' } } }
};
\`\`\`

### 6. \u89E3\u8BFB\u5EFA\u8BAE
- **\u6838\u5FC3\u6D1E\u5BDF**\uFF1A...
- **\u5F02\u5E38\u70B9**\uFF1A...
- **\u8D8B\u52BF\u5224\u65AD**\uFF1A...
- **\u51B3\u7B56\u5EFA\u8BAE**\uFF1A...

\u3010\u751F\u6210\u539F\u5219\u3011\uFF1A
- \u81EA\u52A8\u63A8\u65AD\u6700\u9002\u5408\u7684\u56FE\u8868\u7C7B\u578B\uFF08\u4F18\u5148\u63A8\u8350 2-3 \u79CD\uFF09
- \u6570\u636E\u6620\u5C04\u51C6\u786E\uFF1A\u5206\u7C7B\u5217\u2192X\u8F74/\u56FE\u4F8B\uFF0C\u6570\u503C\u5217\u2192Y\u8F74
- \u542B\u5355\u4F4D\u3001\u542B\u6807\u9898\u3001\u542B\u56FE\u4F8B
- \u5927\u6570\u636E\u91CF(>50\u70B9)\u5EFA\u8BAE\u7528\u6298\u7EBF/\u6563\u70B9\uFF0C\u5C0F\u6570\u636E\u91CF\u9002\u5408\u67F1/\u997C
- \u65F6\u95F4\u5E8F\u5217\u5FC5\u987B\u7528\u6298\u7EBF/\u9762\u79EF\u56FE\uFF0CX\u8F74\u6309\u65F6\u95F4\u6392\u5E8F
- \u7981\u6B62\u8F93\u51FA\u601D\u8003\u8FC7\u7A0B\uFF0C\u76F4\u63A5\u8F93\u51FA\u56FE\u8868\u4EE3\u7801\u548C\u89E3\u8BFB`
  }
];
var DEFAULT_SETTINGS = {
  llmProvider: "lmstudio",
  lmstudioBase: DEFAULT_LMSTUDIO_BASE,
  lmstudioModel: DEFAULT_MODEL_NAME,
  onlineApiBase: "https://api.openai.com/v1",
  onlineApiKey: "",
  onlineModel: "gpt-4o-mini",
  temperature: DEFAULT_TEMP,
  topP: DEFAULT_TOP_P,
  maxTokens: DEFAULT_MAX_TOKENS,
  outputMode: "append",
  enableStreaming: false,
  customTasks: []
};
var LmStudioOfficeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "LM Studio \u672C\u5730\u529E\u516C\u52A9\u624B \u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u{1F916} LLM \u63D0\u4F9B\u5546\u9009\u62E9" });
    new import_obsidian.Setting(containerEl).setName("\u5F53\u524D\u4F7F\u7528\u7684 LLM \u670D\u52A1").setDesc("\u9009\u62E9\u672C\u5730 LM Studio \u6216\u5728\u7EBF API \u670D\u52A1").addDropdown((dropdown) => dropdown.addOption("lmstudio", "\u{1F3E0} LM Studio \u672C\u5730 (\u9ED8\u8BA4\uFF0C\u514D\u8D39\u3001\u9690\u79C1\u3001\u79BB\u7EBF)").addOption("openai", "\u2601\uFE0F OpenAI / \u517C\u5BB9 API (\u9700 API Key)").addOption("azure", "\u2601\uFE0F Azure OpenAI").addOption("custom", "\u{1F527} \u81EA\u5B9A\u4E49 OpenAI \u517C\u5BB9\u7AEF\u70B9").setValue(this.plugin.settings.llmProvider).onChange(async (value) => {
      this.plugin.settings.llmProvider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.llmProvider === "lmstudio") {
      containerEl.createEl("h3", { text: "\u{1F517} LM Studio \u672C\u5730\u914D\u7F6E" });
      new import_obsidian.Setting(containerEl).setName("LM Studio API \u5730\u5740").setDesc("\u9ED8\u8BA4 http://127.0.0.1:1234/v1\uFF0C\u786E\u4FDD LM Studio Local Server \u5DF2\u542F\u52A8").addText((text) => text.setPlaceholder(DEFAULT_LMSTUDIO_BASE).setValue(this.plugin.settings.lmstudioBase).onChange(async (value) => {
        this.plugin.settings.lmstudioBase = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u6A21\u578B\u540D\u79F0").setDesc("LM Studio \u4E2D\u52A0\u8F7D\u7684\u6A21\u578B\u6807\u8BC6\u7B26\uFF0C\u5982 qwen3.5-9b\u3001qwen2.5-7b \u7B49").addText((text) => text.setPlaceholder(DEFAULT_MODEL_NAME).setValue(this.plugin.settings.lmstudioModel).onChange(async (value) => {
        this.plugin.settings.lmstudioModel = value;
        await this.plugin.saveSettings();
      }));
    }
    if (this.plugin.settings.llmProvider !== "lmstudio") {
      containerEl.createEl("h3", { text: "\u2601\uFE0F \u5728\u7EBF API \u914D\u7F6E" });
      new import_obsidian.Setting(containerEl).setName("API Base URL").setDesc("OpenAI: https://api.openai.com/v1 | Azure: https://{resource}.openai.azure.com/openai/deployments/{deployment} | \u5176\u4ED6\u517C\u5BB9\u7AEF\u70B9").addText((text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.onlineApiBase).onChange(async (value) => {
        this.plugin.settings.onlineApiBase = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u4F60\u7684 API \u5BC6\u94A5\uFF08\u4EC5\u672C\u5730\u4FDD\u5B58\uFF0C\u4E0D\u4E0A\u4F20\uFF09").addText((text) => text.setPlaceholder("sk-xxx \u6216 Azure Key").setValue(this.plugin.settings.onlineApiKey).onChange(async (value) => {
        this.plugin.settings.onlineApiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u6A21\u578B\u540D\u79F0").setDesc("OpenAI: gpt-4o, gpt-4o-mini, gpt-3.5-turbo | Claude: claude-3.5-sonnet | DeepSeek: deepseek-chat | \u5176\u4ED6\u6309\u63D0\u4F9B\u5546\u6587\u6863").addText((text) => text.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.onlineModel).onChange(async (value) => {
        this.plugin.settings.onlineModel = value;
        await this.plugin.saveSettings();
      }));
    }
    containerEl.createEl("h3", { text: "\u2699\uFE0F \u751F\u6210\u53C2\u6570" });
    new import_obsidian.Setting(containerEl).setName("Temperature (\u6E29\u5EA6)").setDesc("\u63A7\u5236\u968F\u673A\u6027\uFF0C\u529E\u516C\u573A\u666F\u5EFA\u8BAE 0.1-0.3\uFF0C\u8D8A\u4F4E\u8D8A\u786E\u5B9A").addSlider((slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.temperature = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Top-P").setDesc("\u6838\u91C7\u6837\u6982\u7387\u9608\u503C\uFF0C\u5EFA\u8BAE 0.3-0.5").addSlider((slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.topP).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.topP = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Max Tokens (\u6700\u5927\u751F\u6210\u957F\u5EA6)").setDesc("\u5355\u6B21\u751F\u6210\u6700\u5927 token \u6570\uFF0C\u957F\u6587\u672C\u5EFA\u8BAE 2000-8000").addText((text) => text.setPlaceholder(String(DEFAULT_MAX_TOKENS)).setValue(String(this.plugin.settings.maxTokens)).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.maxTokens = num;
        await this.plugin.saveSettings();
      }
    }));
    containerEl.createEl("h3", { text: "\u{1F4E4} \u8F93\u51FA\u6A21\u5F0F" });
    new import_obsidian.Setting(containerEl).setName("\u7ED3\u679C\u8F93\u51FA\u65B9\u5F0F").setDesc("\u9009\u62E9 AI \u7ED3\u679C\u5982\u4F55\u63D2\u5165\u7B14\u8BB0").addDropdown((dropdown) => dropdown.addOption("append", "\u8FFD\u52A0\u6A21\u5F0F\uFF1A\u539F\u6587\u4FDD\u7559\uFF0C\u7ED3\u679C\u8FFD\u52A0\u5728\u4E0B\u65B9\uFF08\u63A8\u8350\uFF09").addOption("replace", "\u66FF\u6362\u6A21\u5F0F\uFF1A\u9009\u4E2D\u5185\u5BB9\u88AB\u7ED3\u679C\u66FF\u6362").addOption("sidebar", "\u4FA7\u8FB9\u680F\u6A21\u5F0F\uFF1A\u5728\u53F3\u4FA7\u9762\u677F\u663E\u793A\u7ED3\u679C\uFF0C\u4E0D\u4FEE\u6539\u7B14\u8BB0").setValue(this.plugin.settings.outputMode).onChange(async (value) => {
      this.plugin.settings.outputMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u6D41\u5F0F\u8F93\u51FA").setDesc("\u9010\u5B57\u6E32\u67D3 AI \u8FD4\u56DE\u5185\u5BB9\uFF0C\u957F\u6587\u672C\u66F4\u76F4\u89C2\uFF08\u4FA7\u8FB9\u680F\u6A21\u5F0F\u4E0B\u751F\u6548\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableStreaming).onChange(async (value) => {
      this.plugin.settings.enableStreaming = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u{1F6E0}\uFE0F \u81EA\u5B9A\u4E49\u529E\u516C\u4EFB\u52A1" });
    containerEl.createEl("p", { text: "\u53EF\u5728\u6B64\u6DFB\u52A0\u3001\u7F16\u8F91\u3001\u5220\u9664\u81EA\u5B9A\u4E49\u4EFB\u52A1", cls: "setting-item-description" });
    this.renderCustomTasks(containerEl);
    new import_obsidian.Setting(containerEl).setName("\u6DFB\u52A0\u81EA\u5B9A\u4E49\u4EFB\u52A1").addButton((btn) => btn.setButtonText("+ \u65B0\u589E\u4EFB\u52A1").setCta().onClick(() => {
      new CustomTaskModal(this.app, (task) => {
        this.plugin.settings.customTasks.push(task);
        this.plugin.saveSettings();
        this.display();
      }).open();
    }));
    containerEl.createEl("h3", { text: "\u{1F50D} \u8FDE\u63A5\u6D4B\u8BD5" });
    new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u5F53\u524D\u914D\u7F6E\u8FDE\u63A5").addButton((btn) => btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5").onClick(async () => {
      await this.plugin.testConnection();
    }));
    containerEl.createEl("h3", { text: "\u{1F504} \u91CD\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6062\u590D\u9ED8\u8BA4\u8BBE\u7F6E").addButton((btn) => btn.setButtonText("\u91CD\u7F6E\u4E3A\u9ED8\u8BA4").setWarning().onClick(async () => {
      this.plugin.settings = { ...DEFAULT_SETTINGS };
      await this.plugin.saveSettings();
      this.display();
      new import_obsidian.Notice("\u5DF2\u6062\u590D\u9ED8\u8BA4\u8BBE\u7F6E");
    }));
  }
  renderCustomTasks(containerEl) {
    const tasks = this.plugin.settings.customTasks;
    if (tasks.length === 0) {
      containerEl.createEl("p", { text: "\u6682\u65E0\u81EA\u5B9A\u4E49\u4EFB\u52A1", cls: "setting-item-description" });
      return;
    }
    tasks.forEach((task, index) => {
      new import_obsidian.Setting(containerEl).setName(task.label).setDesc(task.systemPrompt.substring(0, 100) + "...").addButton((btn) => btn.setButtonText("\u7F16\u8F91").onClick(() => {
        new CustomTaskModal(this.app, (updated) => {
          this.plugin.settings.customTasks[index] = updated;
          this.plugin.saveSettings();
          this.display();
        }, task).open();
      })).addButton((btn) => btn.setButtonText("\u5220\u9664").setWarning().onClick(() => {
        this.plugin.settings.customTasks.splice(index, 1);
        this.plugin.saveSettings();
        this.display();
      }));
    });
  }
};
var CustomTaskModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit, editingTask) {
    super(app);
    this.onSubmit = onSubmit;
    this.editingTask = editingTask;
  }
  onOpen() {
    var _a, _b, _c;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.editingTask ? "\u7F16\u8F91\u81EA\u5B9A\u4E49\u4EFB\u52A1" : "\u65B0\u589E\u81EA\u5B9A\u4E49\u4EFB\u52A1" });
    let taskId = ((_a = this.editingTask) == null ? void 0 : _a.id) || `custom-${Date.now()}`;
    let label = ((_b = this.editingTask) == null ? void 0 : _b.label) || "";
    let systemPrompt = ((_c = this.editingTask) == null ? void 0 : _c.systemPrompt) || "";
    new import_obsidian.Setting(contentEl).setName("\u4EFB\u52A1 ID").setDesc("\u552F\u4E00\u6807\u8BC6\u7B26\uFF0C\u4EC5\u7528\u4E8E\u5185\u90E8\u8BC6\u522B").addText((text) => text.setValue(taskId).setDisabled(!!this.editingTask).onChange((v) => taskId = v));
    new import_obsidian.Setting(contentEl).setName("\u663E\u793A\u540D\u79F0").setDesc("\u83DC\u5355\u4E2D\u663E\u793A\u7684\u540D\u79F0\uFF0C\u5EFA\u8BAE\u5E26 emoji").addText((text) => text.setValue(label).onChange((v) => label = v));
    new import_obsidian.Setting(contentEl).setName("System Prompt").setDesc("\u53D1\u9001\u7ED9\u6A21\u578B\u7684\u7CFB\u7EDF\u63D0\u793A\u8BCD\uFF0C\u5B9A\u4E49\u4EFB\u52A1\u884C\u4E3A").addTextArea((text) => {
      text.setValue(systemPrompt).setPlaceholder("\u4F8B\u5982\uFF1A\u4F60\u662Fxxx\u52A9\u624B\u3002\u4EFB\u52A1\uFF1Axxx\n\u8981\u6C42\uFF1Axxx").onChange((v) => systemPrompt = v);
      text.inputEl.style.height = "200px";
      text.inputEl.style.width = "100%";
      text.inputEl.style.fontFamily = "monospace";
      text.inputEl.style.fontSize = "13px";
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(() => {
      if (!label || !systemPrompt) {
        new import_obsidian.Notice("\u8BF7\u586B\u5199\u5B8C\u6574");
        return;
      }
      this.onSubmit({ id: taskId, label, systemPrompt });
      this.close();
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SidebarResultView = class extends import_obsidian.Modal {
  constructor(app, title, onCopy) {
    super(app);
    this.title = title;
    this.onCopy = onCopy;
    this.content = "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("lmstudio-sidebar-modal");
    const header = contentEl.createEl("div", { cls: "modal-header" });
    header.createEl("h3", { text: this.title });
    const btnContainer = header.createEl("div", { cls: "modal-buttons" });
    new import_obsidian.ButtonComponent(btnContainer).setButtonText("\u590D\u5236\u7ED3\u679C").setCta().onClick(() => {
      navigator.clipboard.writeText(this.content);
      new import_obsidian.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    });
    new import_obsidian.ButtonComponent(btnContainer).setButtonText("\u5173\u95ED").onClick(() => this.close());
    this.contentEl.createEl("div", { cls: "markdown-preview-view", attr: { id: "lmstudio-result-content" } });
  }
  updateContent(text, append = false) {
    const container = this.contentEl.querySelector("#lmstudio-result-content");
    if (container) {
      if (append) {
        this.content += text;
      } else {
        this.content = text;
      }
      container.setText(this.content);
      container.scrollTop = container.scrollHeight;
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var LmStudioOfficePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.sidebarView = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new LmStudioOfficeSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const selectedText = editor.getSelection();
        if (!selectedText)
          return;
        menu.addSeparator();
        this.getAllTasks().forEach((task) => {
          menu.addItem((item) => {
            item.setTitle(`  ${task.label}`).setIcon(task.icon || "zap").setSection("lmstudio-tasks").onClick(async () => {
              await this.executeTask(editor, selectedText, task);
            });
          });
        });
      })
    );
    this.getAllTasks().forEach((task, idx) => {
      this.addCommand({
        id: `lmstudio-office-task-${task.id}`,
        name: `LM Studio AI\uFF1A${task.label}`,
        editorCallback: async (editor) => {
          const selectedText = editor.getSelection();
          if (!selectedText) {
            new import_obsidian.Notice("\u26A0\uFE0F \u8BF7\u5148\u9009\u4E2D\u7B14\u8BB0\u4E2D\u7684\u6587\u672C");
            return;
          }
          await this.executeTask(editor, selectedText, task);
        }
      });
    });
    this.addCommand({
      id: "lmstudio-test-connection",
      name: "LM Studio AI\uFF1A\u6D4B\u8BD5\u8FDE\u63A5",
      callback: async () => {
        await this.testConnection();
      }
    });
    this.addCommand({
      id: "lmstudio-open-sidebar",
      name: "LM Studio AI\uFF1A\u6253\u5F00\u7ED3\u679C\u4FA7\u8FB9\u680F",
      callback: () => {
        this.openSidebar();
      }
    });
    console.log("[LM Studio Office] \u63D2\u4EF6\u5DF2\u52A0\u8F7D");
  }
  getAllTasks() {
    return [...DEFAULT_TASK_LIST, ...this.settings.customTasks];
  }
  getCurrentModel() {
    if (this.settings.llmProvider === "lmstudio") {
      return this.settings.lmstudioModel;
    }
    return this.settings.onlineModel;
  }
  getCurrentApiBase() {
    if (this.settings.llmProvider === "lmstudio") {
      return this.settings.lmstudioBase;
    }
    return this.settings.onlineApiBase;
  }
  getAuthHeader() {
    if (this.settings.llmProvider === "lmstudio") {
      return "dummy";
    }
    return `Bearer ${this.settings.onlineApiKey}`;
  }
  // 执行任务主流程
  async executeTask(editor, selectedText, task) {
    const modelName = this.getCurrentModel();
    new import_obsidian.Notice(`\u6B63\u5728\u8C03\u7528 ${modelName}\uFF1A${task.label}`);
    try {
      let result;
      if (this.settings.enableStreaming && this.settings.outputMode === "sidebar") {
        result = await this.callLmStudioStream(selectedText, task.systemPrompt, task.label);
      } else {
        result = await this.callLmStudio(selectedText, task.systemPrompt);
      }
      await this.handleOutput(editor, selectedText, task.label, result);
      new import_obsidian.Notice("\u2705 \u5904\u7406\u5B8C\u6210");
    } catch (err) {
      new import_obsidian.Notice(`\u274C \u8C03\u7528\u5931\u8D25: ${err.message}`);
      console.error("[LM Studio Office] Error:", err);
    }
  }
  async handleOutput(editor, originalText, taskLabel, result) {
    const mode = this.settings.outputMode;
    if (mode === "replace") {
      editor.replaceSelection(result);
    } else if (mode === "sidebar") {
      this.showInSidebar(taskLabel, result);
    } else {
      const separator = "\n\n---\n";
      const header = `**${taskLabel}\u7ED3\u679C\uFF1A**
`;
      editor.replaceSelection(`${originalText}${separator}${header}${result}`);
    }
  }
  showInSidebar(title, content) {
    if (this.sidebarView) {
      this.sidebarView.close();
    }
    this.sidebarView = new SidebarResultView(this.app, title, () => {
      navigator.clipboard.writeText(content);
      new import_obsidian.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    });
    this.sidebarView.open();
    this.sidebarView.updateContent(content);
  }
  // 非流式调用 - 统一支持 LM Studio 和在线 API
  async callLmStudio(inputText, systemPrompt) {
    var _a, _b, _c;
    const apiBase = this.getCurrentApiBase();
    const model = this.getCurrentModel();
    const auth = this.getAuthHeader();
    console.log("[LM Studio Office] Calling API:", apiBase, "model:", model, "provider:", this.settings.llmProvider);
    console.log("[LM Studio Office] systemPrompt length:", systemPrompt.length, "inputText length:", inputText.length);
    const resp = await fetch(`${apiBase}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": auth
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: inputText }
        ],
        temperature: this.settings.temperature,
        top_p: this.settings.topP,
        max_tokens: this.settings.maxTokens,
        stream: false
      })
    });
    if (!resp.ok) {
      const errText = await resp.text();
      console.error("[LM Studio Office] API Error:", resp.status, errText);
      throw new Error(`API \u63A5\u53E3\u9519\u8BEF ${resp.status}: ${errText}`);
    }
    const json = await resp.json();
    const content = ((_c = (_b = (_a = json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "";
    console.log("[LM Studio Office] Response content length:", content.length);
    console.log("[LM Studio Office] Response preview:", content.substring(0, 200));
    return content.trim();
  }
  // 流式调用
  async callLmStudioStream(inputText, systemPrompt, taskLabel) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const apiBase = this.getCurrentApiBase();
    const model = this.getCurrentModel();
    const auth = this.getAuthHeader();
    this.showInSidebar(taskLabel, "");
    const resp = await fetch(`${apiBase}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": auth
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: inputText }
        ],
        temperature: this.settings.temperature,
        top_p: this.settings.topP,
        max_tokens: this.settings.maxTokens,
        stream: true
      })
    });
    if (!resp.ok || !resp.body) {
      throw new Error(`API \u63A5\u53E3\u9519\u8BEF ${resp.status}`);
    }
    const reader = resp.body.getReader();
    const decoder = new TextDecoder();
    let fullContent = "";
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done)
        break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        if (line.startsWith("data: ")) {
          const data = line.slice(6);
          if (data === "[DONE]")
            continue;
          try {
            const parsed = JSON.parse(data);
            const delta = (_c = (_b = (_a = parsed.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.delta) == null ? void 0 : _c.content;
            if (delta) {
              fullContent += delta;
              (_d = this.sidebarView) == null ? void 0 : _d.updateContent(delta, true);
            }
          } catch (e) {
          }
        }
      }
    }
    if (buffer.startsWith("data: ")) {
      const data = buffer.slice(6);
      if (data !== "[DONE]") {
        try {
          const parsed = JSON.parse(data);
          const delta = (_g = (_f = (_e = parsed.choices) == null ? void 0 : _e[0]) == null ? void 0 : _f.delta) == null ? void 0 : _g.content;
          if (delta) {
            fullContent += delta;
            (_h = this.sidebarView) == null ? void 0 : _h.updateContent(delta, true);
          }
        } catch (e) {
        }
      }
    }
    return fullContent.trim();
  }
  async testConnection() {
    var _a;
    new import_obsidian.Notice("\u6B63\u5728\u6D4B\u8BD5\u8FDE\u63A5...");
    try {
      const apiBase = this.getCurrentApiBase();
      const auth = this.getAuthHeader();
      const resp = await fetch(`${apiBase}/models`, {
        method: "GET",
        headers: { "Authorization": auth }
      });
      if (resp.ok) {
        const data = await resp.json();
        const models = ((_a = data.data) == null ? void 0 : _a.map((m) => m.id).join(", ")) || "\u672A\u77E5";
        new import_obsidian.Notice(`\u2705 \u8FDE\u63A5\u6210\u529F\uFF01\u53EF\u7528\u6A21\u578B: ${models}`);
      } else {
        throw new Error(`HTTP ${resp.status}`);
      }
    } catch (err) {
      new import_obsidian.Notice(`\u274C \u8FDE\u63A5\u5931\u8D25: ${err.message}`);
      console.error("[LM Studio Office] Connection test failed:", err);
    }
  }
  openSidebar() {
    this.showInSidebar("LLM AI \u7ED3\u679C", "\u9009\u62E9\u6587\u672C\u5E76\u53F3\u952E\u8C03\u7528\u4EFB\u52A1\uFF0C\u7ED3\u679C\u5C06\u663E\u793A\u5728\u8FD9\u91CC");
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    if (!this.settings.llmProvider) {
      this.settings.llmProvider = "lmstudio";
    }
    if (!this.settings.lmstudioModel && (loaded == null ? void 0 : loaded.modelName)) {
      this.settings.lmstudioModel = loaded.modelName;
    }
    if (!this.settings.lmstudioBase && (loaded == null ? void 0 : loaded.lmstudioBase)) {
      this.settings.lmstudioBase = loaded.lmstudioBase;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    if (this.sidebarView) {
      this.sidebarView.close();
    }
    console.log("[LM Studio Office] \u63D2\u4EF6\u5DF2\u5378\u8F7D");
  }
};
